name: techtestvascomm
description: TECHNICAL ASSESSMENT PT. VASCOMM SOLUSI TEKNOLOGI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^4.0.6
  flutter_flavor: ^3.1.1
  flutter_secure_storage: ^8.0.0
  form_validator: ^2.1.1
  font_awesome_flutter: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
